version: "3.0"

services:

  php-fpm-api.local:
    build: ./php-fpm
    depends_on:
      - db.local
    volumes:
      - ../api:/app
      - ./php-fpm/php-api.ini:/usr/local/etc/php/conf.d/php-app.ini:ro

  nginx-api.local:
    image: nginx:alpine
    depends_on:
      - php-fpm-api.local
    volumes:
      - ./nginx/api.conf:/etc/nginx/conf.d/default.conf:ro
      - ../api:/app:ro


  php-fpm-auth.local:
    build: ./php-fpm
    depends_on:
      - db.local
    volumes:
      - ../auth:/app
      - ./php-fpm/php-auth.ini:/usr/local/etc/php/conf.d/php-app.ini:ro


  nginx-auth.local:
    image: nginx:alpine
    depends_on:
      - php-fpm-auth.local
    volumes:
      - ./nginx/auth.conf:/etc/nginx/conf.d/default.conf:ro
      - ../auth:/app:ro

  nginx-front.local:
    image: nginx:alpine
    volumes:
      - ./nginx/front.conf:/etc/nginx/conf.d/default.conf:ro
      - ../front:/app:ro

  db.local:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=oauth2
    ports:
      - 3306:3306
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./db/custom.cnf:/etc/mysql/conf.d/custom.cnf

  ha-proxy.local:
    image: haproxy:alpine
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro
    ports:
      - 80:80
      - 443:443
    links:
      - nginx-front.local
      - nginx-api.local
      - nginx-auth.local

